services:
  - type: web
    name: django-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r ./backend/requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ProyectoFinal.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
