services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:10000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
