# Generated by Django 5.1.7 on 2025-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('fantasy', 'Fantasía'), ('scifi', 'Ciencia Ficción'), ('horror', 'Terror'), ('thriller', 'Suspenso'), ('historical', 'Histórica'), ('classic', 'Clásico'), ('manga', 'Manga')], default='fantasy', max_length=20)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
